# Generated by Django 5.0.6 on 2024-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_remove_products_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="decription",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
